// Enums matching Prisma schema
const Role = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  CUSTOMER: 'CUSTOMER',
  SUPPLIER: 'SUPPLIER',
  STAFF: 'STAFF'
};

const ProductType = {
  RAW: 'RAW',
  SEMI_FINISHED: 'SEMI_FINISHED',
  FINISHED: 'FINISHED'
};

const TransactionType = {
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  TRANSFER: 'TRANSFER',
  USAGE: 'USAGE',
  ADJUSTMENT: 'ADJUSTMENT',
  MANUAL: 'MANUAL',
  RETURN: 'RETURN'
};

const AlertType = {
  LOW_STOCK: 'LOW_STOCK',
  OVERSTOCK: 'OVERSTOCK',
  EXPIRY: 'EXPIRY',
  REORDER: 'REORDER'
};

const POStatus = {
  PENDING: 'PENDING',
  RECEIVED: 'RECEIVED',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  CANCELLED: 'CANCELLED'
};

const SOStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const MovementType = {
  IN: 'IN',
  OUT: 'OUT'
};

const BatchStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

// Business constants
const STOCK_THRESHOLDS = {
  LOW_STOCK_PERCENTAGE: 0.1, // 10% of average stock
  OVERSTOCK_MULTIPLIER: 3,   // 3x average stock
  REORDER_POINT_MULTIPLIER: 1.5 // 1.5x average consumption
};

const COST_CALCULATION = {
  DECIMAL_PRECISION: 6,
  DEFAULT_CURRENCY: 'USD'
};

const PAGINATION = {
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100
};

// Security constants
const SECURITY = {
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_REQUIRE_UPPERCASE: true,
  PASSWORD_REQUIRE_LOWERCASE: true,
  PASSWORD_REQUIRE_NUMBERS: true,
  PASSWORD_REQUIRE_SYMBOLS: true,
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 30,
  SESSION_TIMEOUT_HOURS: 8,
  REFRESH_TOKEN_EXPIRY_DAYS: 30
};

// Tenant constants
const TENANT = {
  MAX_USERS_PER_TENANT: 1000,
  MAX_WAREHOUSES_PER_TENANT: 50,
  MAX_ITEMS_PER_TENANT: 10000,
  DEFAULT_PLAN: 'BASIC',
  PLANS: ['BASIC', 'PROFESSIONAL', 'ENTERPRISE']
};

module.exports = {
  Role,
  ProductType,
  TransactionType,
  AlertType,
  POStatus,
  SOStatus,
  MovementType,
  BatchStatus,
  STOCK_THRESHOLDS,
  COST_CALCULATION,
  PAGINATION,
  SECURITY,
  TENANT
};
